# New Software Development
# Bootstrap new project then iterate with feature-dev
id: new-app-dev
name: New Software Development
version: 2
description: |
  Bootstrap a new project quickly.
  Scaffold → first feature → hand off to feature-dev workflow for iteration.

context:
  repo: /Users/petersykim/clawd/tmp/antfarm-sandbox-repo

agents:
  - id: planner
    name: Planner
    role: analysis
    description: Plans minimal viable scaffold + first feature.
    workspace:
      baseDir: agents/planner
      files:
        AGENTS.md: agents/planner/AGENTS.md

  - id: setup
    name: Setup
    role: setup
    description: Scaffolds project with build/test/CI and baseline.
    workspace:
      baseDir: agents/setup
      files:
        AGENTS.md: agents/setup/AGENTS.md

  - id: developer
    name: Developer
    role: coding
    description: Implements first feature with tests.
    workspace:
      baseDir: agents/developer
      files:
        AGENTS.md: agents/developer/AGENTS.md

  - id: verifier
    name: Verifier
    role: verification
    description: Validates acceptance criteria and tests.
    workspace:
      baseDir: agents/verifier
      files:
        AGENTS.md: agents/verifier/AGENTS.md

  - id: tester
    name: Tester
    role: testing
    description: Runs E2E tests.
    workspace:
      baseDir: agents/tester
      files:
        AGENTS.md: agents/tester/AGENTS.md

  - id: reviewer
    name: Reviewer
    role: analysis
    description: Reviews code quality.
    workspace:
      baseDir: agents/reviewer
      files:
        AGENTS.md: agents/reviewer/AGENTS.md

steps:
  - id: plan
    agent: planner
    input: |
      Plan minimal bootstrap for this app.

      TASK: {{task}}

      Create ≤5 stories for:
      - Project scaffold (stack, build, test, CI)
      - One core feature (prove the stack works)

      Reply with:
      STATUS: done
      REPO: /path/to/repo
      BRANCH: bootstrap/app-name
      STORIES_JSON: [...]
    expects: "STATUS: done"
    max_retries: 2

  - id: setup
    agent: setup
    input: |
      Scaffold the project.

      TASK: {{task}}
      REPO: {{repo}}
      BRANCH: {{branch}}

      Choose stack, set up build/test/CI, create baseline.
      Document decisions in progress.txt.

      Reply with:
      STATUS: done
      BUILD_CMD: command
      TEST_CMD: command
      BASELINE: result
    expects: "STATUS: done"
    max_retries: 2

  - id: implement
    agent: developer
    type: loop
    loop:
      context_key: stories
      iterate_over: "{{stories}}"
    input: |
      Implement bootstrap story.

      STORY: {{current_story}}
      REPO: {{repo}}
      BRANCH: {{branch}}

      Build it, write tests, commit.

      Reply with:
      STATUS: done
      CHANGES: summary
      TESTS: what was tested
    expects: "STATUS: done"
    max_retries: 2

  - id: verify
    agent: verifier
    type: loop
    loop:
      context_key: stories
      iterate_over: "{{stories}}"
    input: |
      Verify story.

      STORY: {{current_story}}
      OUTPUT: {{implement_output}}

      Check: code works, tests pass.

      Reply: STATUS: done + VERIFIED
      OR: STATUS: retry + ISSUES
    expects: "STATUS: done"
    max_retries: 2

  - id: test
    agent: tester
    input: |
      Run bootstrap E2E tests.

      REPO: {{repo}}
      BRANCH: {{branch}}

      Validate core flow works.

      Reply: STATUS: done + RESULTS
      OR: STATUS: retry + FAILURES
    expects: "STATUS: done"
    max_retries: 2

  - id: review
    agent: reviewer
    input: |
      Review bootstrap quality.

      REPO: {{repo}}
      BRANCH: {{branch}}

      Check: patterns, tests, build works.

      Reply: STATUS: done + SUMMARY
    expects: "STATUS: done"
    max_retries: 2

cron:
  interval_ms: 300000
