# Educational Lesson Module Development
# Build lesson modules for existing learning platform
id: lesson-module
name: Educational Lesson Module
version: 2
description: |
  Develop lesson modules for kids' learning platform.
  Assumes platform exists; focuses on module-level features (content, activities, assessments).

context:
  repo: /Users/petersykim/clawd/tmp/antfarm-sandbox-repo

agents:
  - id: planner
    name: Planner
    role: analysis
    description: Breaks module into implementable stories.
    workspace:
      baseDir: agents/planner
      files:
        AGENTS.md: agents/planner/AGENTS.md

  - id: developer
    name: Developer
    role: coding
    description: Implements module features with tests.
    workspace:
      baseDir: agents/developer
      files:
        AGENTS.md: agents/developer/AGENTS.md

  - id: verifier
    name: Verifier
    role: verification
    description: Validates acceptance criteria and tests.
    workspace:
      baseDir: agents/verifier
      files:
        AGENTS.md: agents/verifier/AGENTS.md

  - id: tester
    name: Tester
    role: testing
    description: Runs E2E module flows.
    workspace:
      baseDir: agents/tester
      files:
        AGENTS.md: agents/tester/AGENTS.md

  - id: reviewer
    name: Reviewer
    role: analysis
    description: Reviews code quality and patterns.
    workspace:
      baseDir: agents/reviewer
      files:
        AGENTS.md: agents/reviewer/AGENTS.md

steps:
  - id: plan
    agent: planner
    input: |
      Break this module into ≤15 implementable stories.

      TASK: {{task}}

      Order: schema/data → logic → UI → tests.
      Each story: fits one session, has tests, includes "Typecheck passes".

      Reply with:
      STATUS: done
      REPO: /path/to/repo
      BRANCH: module/feature-name
      STORIES_JSON: [...]
    expects: "STATUS: done"
    max_retries: 2

  - id: implement
    agent: developer
    type: loop
    loop:
      over: stories
      completion: all_done
      fresh_session: true
      verify_each: true
      verify_step: verify
    input: |
      Implement one story for this module.

      STORY: {{current_story}}
      REPO: {{repo}}
      BRANCH: {{branch}}

      Steps: read progress.txt → implement → write tests → commit.

      Reply with:
      STATUS: done
      CHANGES: summary
      TESTS: what was tested
    expects: "STATUS: done"
    max_retries: 2

  - id: verify
    agent: verifier
    type: loop
    loop:
      over: stories
      completion: all_done
      fresh_session: true
      verify_each: false
    input: |
      Verify story meets acceptance criteria.

      STORY: {{current_story}}
      OUTPUT: {{implement_output}}

      Check: code exists, criteria met, tests pass, typecheck passes.

      Reply: STATUS: done + VERIFIED: details
      OR: STATUS: retry + ISSUES: gaps
    expects: "STATUS: done"
    max_retries: 2

  - id: test
    agent: tester
    input: |
      Run module E2E tests.

      REPO: {{repo}}
      BRANCH: {{branch}}

      Test module flows end-to-end.

      Reply: STATUS: done + RESULTS
      OR: STATUS: retry + FAILURES
    expects: "STATUS: done"
    max_retries: 2

  - id: pr
    agent: developer
    input: |
      Create PR.

      REPO: {{repo}}
      BRANCH: {{branch}}

      Use: gh pr create

      Reply with:
      STATUS: done
      PR: URL
    expects: "STATUS: done"
    max_retries: 2

  - id: review
    agent: reviewer
    input: |
      Review PR.

      PR: {{pr}}

      Check: quality, tests, patterns.

      Reply: STATUS: done + DECISION: approved
      OR: STATUS: retry + DECISION: changes_requested + FEEDBACK
    expects: "STATUS: done"
    max_retries: 3

cron:
  interval_ms: 300000
