# UI/UX Design & Implementation
# Polish existing projects with better UI/UX
id: ui-ux-dev
name: UI/UX Design & Implementation
version: 2
description: |
  Add or improve UI for existing projects.
  Assumes app exists; focuses on design → implementation → verification.

context:
  repo: /Users/petersykim/clawd/tmp/antfarm-sandbox-repo

agents:
  - id: designer
    name: Designer
    role: design
    description: Creates designs and component specs.

  - id: developer
    name: Developer
    role: coding
    description: Implements UI with accessibility and responsiveness.

  - id: verifier
    name: Verifier
    role: verification
    description: Validates UI matches design and meets criteria.

  - id: tester
    name: Tester
    role: testing
    description: Runs E2E UI tests.

  - id: reviewer
    name: Reviewer
    role: analysis
    description: Reviews design fidelity and code quality.

steps:
  - id: design
    agent: designer
    input: |
      Create UI designs for this feature.

      TASK: {{task}}

      Produce:
      - Component designs (Figma or mockups)
      - Design tokens (colors, spacing, typography)
      - Interaction states
      - Accessibility annotations

      Reply with:
      STATUS: done
      REPO: /path/to/repo
      BRANCH: ui/feature-name
      DESIGN_SUMMARY: what was designed
      STORIES_JSON: [implementation stories]
    expects: "STATUS: done"
    max_retries: 2

  - id: implement
    agent: developer
    type: loop
    loop:
      context_key: stories
      iterate_over: "{{stories}}"
    input: |
      Implement UI for this story.

      STORY: {{current_story}}
      REPO: {{repo}}
      BRANCH: {{branch}}
      DESIGN: {{design_summary}}

      Build component with: responsive behavior, accessibility, design tokens.
      Write tests. Commit: feat(ui): story-id - title

      Reply with:
      STATUS: done
      CHANGES: summary
      TESTS: what was tested
    expects: "STATUS: done"
    max_retries: 2

  - id: verify
    agent: verifier
    type: loop
    loop:
      context_key: stories
      iterate_over: "{{stories}}"
    input: |
      Verify UI matches design and works.

      STORY: {{current_story}}
      OUTPUT: {{implement_output}}

      Check: visual fidelity, accessibility, tests pass.

      Reply: STATUS: done + VERIFIED
      OR: STATUS: retry + ISSUES
    expects: "STATUS: done"
    max_retries: 2

  - id: test
    agent: tester
    input: |
      Run UI E2E tests.

      REPO: {{repo}}
      BRANCH: {{branch}}

      Test flows, accessibility, responsiveness.

      Reply: STATUS: done + RESULTS
      OR: STATUS: retry + FAILURES
    expects: "STATUS: done"
    max_retries: 2

  - id: pr
    agent: developer
    input: |
      Create PR with screenshots.

      REPO: {{repo}}
      BRANCH: {{branch}}

      Use: gh pr create

      Reply with:
      STATUS: done
      PR: URL
    expects: "STATUS: done"
    max_retries: 2

  - id: review
    agent: reviewer
    input: |
      Review PR.

      PR: {{pr}}

      Check: design fidelity, quality, accessibility, tests.

      Reply: STATUS: done + DECISION: approved
      OR: STATUS: retry + DECISION: changes_requested + FEEDBACK
    expects: "STATUS: done"
    max_retries: 3

cron:
  interval_ms: 300000
